version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - project-service
      - task-service
      - user-service
    environment:
      - REACT_APP_AUTH_SERVICE_URL=http://auth-service:4000
      - REACT_APP_PROJECT_SERVICE_URL=http://project-service:4001
      - REACT_APP_TASK_SERVICE_URL=http://task-service:4002
      - REACT_APP_USER_SERVICE_URL=http://user-service:4003

  auth-service:
    build:
      context: ./backend/services/auth-service
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=authdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  project-service:
    build:
      context: ./backend/services/project-service
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=development
      - PORT=4001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=projectdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  task-service:
    build:
      context: ./backend/services/task-service
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=development
      - PORT=4002
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=taskdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  user-service:
    build:
      context: ./backend/services/user-service
      dockerfile: Dockerfile
    ports:
      - "4003:4003"
    environment:
      - NODE_ENV=development
      - PORT=4003
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=userdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=authdb,projectdb,taskdb,userdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh

volumes:
  postgres_data:
