apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres in base64
  password: cG9zdGdyZXM=  # postgres in base64
  host: cG9zdGdyZXMtZGI=  # postgres-db in base64
